apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/jenkins-x-apps/jx-app-jacoco:{{.VERSION}}"
  artifacts:
  - imageName: jenkins-x-apps/jx-app-jacoco
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/jenkins-x-apps/jx-app-jacoco:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-app-jacoco
        chartPath: charts/jx-app-jacoco
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/jenkins-x-apps/jx-app-jacoco"
          image.tag: "{{.DIGEST_HEX}}"
